apiVersion: v1
kind: Service
metadata:
  name: my-nginx-svc
  labels:
    app: nginx-deployment
  annotations:
    oci.oraclecloud.com/load-balancer-type: "lb"
spec:
  loadBalancerIP: 130.162.214.207
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: nginx-deployment